### ISSUE TITLE
Gelid freezing attack not being blocked by leather armor

### ISSUE THREAD

**Issue by Warhand** [Faboslav/variants-and-ventures#11]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.17

### Mod version information

1.0.2

### Expected Behavior

The freezing effect should be blocked or mitigated while the target is wearing at least one piece of leather armor.

### Actual Behavior

The target is affected by the same amount of freezing for the same amount of time

### Reproduction Steps

1. Spawn gelid
2. Allow it to attack a target
3. Allow it to attack a second target with leather armor
4. Observe difference

**Comment by Faboslav** [comment]
Will be included in the next update.
