### ISSUE TITLE
[1.20.1] Crash on startup

### ISSUE THREAD

**Issue by BugmanBugman** [Faboslav/variants-and-ventures#12]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

 47.2.32

### Mod version information

1.0.2

### Reproduction Steps

Start up the game and it crashes

### Crash Report and latest.log

https://bytebin.lucko.me/KAQLq5dyoO

**Comment by Faboslav** [comment]
Can you try without the embedium thing please?

**Comment by BugmanBugman** [comment]
It doesn't crash anymore! Weird?

**Comment by Faboslav** [comment]
Then its something bad in embedium mod

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/b59591d9483e86b0ae0622a15ec32d4c
Nvm, tested without embeddium and it still crashes bruv

**Comment by BugmanBugman** [comment]
Any updates on this?

**Comment by Faboslav** [comment]
I am sorry, currently not, i am little bit busy right now, but i will have time to do some fixing soon.

**Comment by Faboslav** [comment]
Tested vanilla minecraft just with forge, and this is 100% caused by some other mod, maybe `zeta_forge`, maybe some other mod, i double checked my registrations, everything is on correct places.
