### ISSUE TITLE
Rendering Overlay Exception For Skull [1.19.2] [Forge]

### ISSUE THREAD

**Issue by xNexusACS** [Faboslav/variants-and-ventures#19]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.3.0

### Mod version information

1.0.3

### Expected Behavior

The mod should load

### Actual Behavior

Minecraft crash on the startup

### Reproduction Steps

1. Download and Install 1.0.3 for forge
2. Start Minecraft

### Screenshots & files

[crash-2024-06-21_13.43.51-client.txt](https://github.com/user-attachments/files/15927079/crash-2024-06-21_13.43.51-client.txt)

Line 107 In the Crash Log File for more information.

**Comment by Faboslav** [comment]
Use forge `43.4.0` or higher, this is a forge bug.

**Comment by xNexusACS** [comment]
okay

**Comment by Faboslav** [comment]
Should be fixed with the new 1.0.4 release :).
