### ISSUE TITLE
Murk should be compatible with Fresh Animations.

### ISSUE THREAD

**Issue by makumaku1974** [Faboslav/variants-and-ventures#21]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.15.11

### Mod version information

1.0.3

### Expected Behavior

Murk should be rendered in fresh animations

### Actual Behavior

Murk is isolated with other mobs like Verdant, Thicket, and Gelid which they are able to move with Fresh Animations.

### Reproduction Steps

1. Spawn the Murk and observe between Verdant, Thicket and Gelid.

### Screenshots & files

![2024-07-03_10 48 23](https://github.com/Faboslav/variants-and-ventures/assets/129804277/8b3bad9a-9e74-4b61-8ae3-0498fc06f29c)

**Comment by digi2303** [comment]
In later releases Faboslav(the owner of the mod) will add a built-in resource pack for the compat.

**Comment by makumaku1974** [comment]
No rush. Ill keep updating.

**Comment by Faboslav** [comment]
Should be fixed with the new 1.0.4 release :).
