### ISSUE TITLE
REI rendering crash

### ISSUE THREAD

**Issue by perci100** [Faboslav/variants-and-ventures#23]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.15.11 (Fabric)

### Mod version information

1.04

### Expected Behavior

Able to search 'skull' or 'head' in REI safely.

### Actual Behavior

REI crashes instantly for failing to render entity. 'Murk skull' or 'gelid head'.

### Reproduction Steps

Search for anything related to skulls or heads in REI.

### Screenshots & files

[crash-2024-07-23_11.24.32-client.txt](https://github.com/user-attachments/files/16347363/crash-2024-07-23_11.24.32-client.txt)
https://mclo.gs/IRSWbyW

**Comment by Faboslav** [comment]
Hello, how about without REI, just the creative inventory, does it crash too?

**Comment by perci100** [comment]
> Hello, how about without REI, just the creative inventory, does it crash too?

Just tested, same issue, searched 'head' in creative inventory and scrolled down, froze and crashed.

https://mclo.gs/BvLJvRS
[crash-2024-07-23_18.47.16-client.txt](https://github.com/user-attachments/files/16352533/crash-2024-07-23_18.47.16-client.txt)

**Comment by Faboslav** [comment]
Thanks for the context, with latest release i thought that i solved this issue, but it seems like its solved for the forge, but introduced in the fabric, i am currently thinking of scrapping the head items all together.

**Comment by pokesmells** [comment]
> Thanks for the context, with latest release i thought that i solved this issue, but it seems like its solved for the forge, but introduced in the fabric, i am currently thinking of scrapping the head items all together.

Can confirm this is still persistent as of today, is there any update to this? https://mclo.gs/Yc9cBja

**Comment by axijiku** [comment]
Hey very cool mod! Unfortunately, it seems to crash my game in the creative menu whenever I look up the mod or scroll past it in the menu. I have a crash log here: 
[crash-2024-08-07_16.48.14-client.txt](https://github.com/user-attachments/files/16535747/crash-2024-08-07_16.48.14-client.txt) it also seems to make a mention of a skull. I'm playing on Fabric 1.20.1.

**Comment by Faboslav** [comment]
Yeah, i am just unable to fix such a thing (that never happened in any of my mods), so sadly i decided i will scape the custom heads feature, which is not that important anyway

**Comment by axijiku** [comment]
> Yeah, i am just unable to fix such a thing (that never happened in any of my mods), so sadly i decided i will scape the custom heads feature, which is not that important anyway

Ah alright, any idea when a fabric version without the heads could be available?

**Comment by Faboslav** [comment]
Probably sometime today, will try to release this ASAP :).

**Comment by Faboslav** [comment]
Should be fixed with the 1.0.5 release available here on github, CF or Modrinth :).

**Comment by axijiku** [comment]
Thank you for the fix man! Really appreciate it.
