### ISSUE TITLE
items in creative tab include spawn eggs invisible

### ISSUE THREAD

**Issue by BugmanBugman** [Faboslav/variants-and-ventures#25]
### Minecraft version information

1.21.1

### Mod loader information

Forge

### Mod loader version information

21.1.20

### Mod version information

 1.0.5

### Expected Behavior

visible items

### Actual Behavior

invisible items

### Reproduction Steps

go to the creative tba

### Screenshots & files

![2024-08-18_16 17 42_2](https://github.com/user-attachments/assets/cd9d5d36-4b22-413b-9dd2-7ea18d9b6256)
![2024-08-18_16 17 43](https://github.com/user-attachments/assets/80be3627-5207-4015-be41-20c7db624a11)

**Comment by Faboslav** [comment]
Hello there, thanks for the report! I am aware of the problem and i will need to do some more debugging to find out why this is happening only on the forge/neoforge side and hopefully fix this later.

**Comment by Faboslav** [comment]
Should be fixed with 1.0.6 :).
