### ISSUE TITLE
Skeletons become immobilized upon naturally spawning

### ISSUE THREAD

**Issue by OliverDK75** [Faboslav/variants-and-ventures#26]
### Minecraft version information

1.20.2

### Mod loader information

Fabric

### Mod loader version information

Fabric 0.15.11

### Mod version information

1.20.2-1.0.5

### Expected Behavior

Skeletons not being immobilized upon naturally spawning

### Actual Behavior

All skeletons that spawn in naturally, dont move, faces south, can still shoot though, but completely immobilized.

### Reproduction Steps

Loading up the mod and a world. Note: I have tested if it was when the mod was on or not. Everytime it was enabled, Skeletons would create this behavior (only when naturally spawning) and when the mod was disabled, they could move again.

### Screenshots & files

![2024-08-21_17 58 55](https://github.com/user-attachments/assets/3d39f5fb-55fb-42d2-b6ab-93bea0c9fc46)
![2024-08-21_17 59 01](https://github.com/user-attachments/assets/d6dd2005-d995-42b8-a67d-221e98828609)

**Comment by Faboslav** [comment]
Hello there, can you try to disable the `enableKeyframeAnimationsForZombieAndItsVariants` and `enableKeyframeAnimationsForSkeletonAndItsVariants` in the config, either via modmenu/catalogue or via the json file?

**Comment by Faboslav** [comment]
@OliverDK75 Any results?

**Comment by Faboslav** [comment]
Should be fixed with 1.0.6 :).
