### ISSUE TITLE
thicket not rendering corectly (heavily modded)

### ISSUE THREAD

**Issue by PabloDnSS** [Faboslav/variants-and-ventures#3]
### Minecraft version information

1.201

### Mod loader information

Forge

### Mod loader version information

forge 47.2.20

### Mod version information

1.0.1

### Expected Behavior

/

### Actual Behavior

/

### Reproduction Steps

/

### Screenshots & files

![2024-03-19_14 34 50](https://github.com/Faboslav/variants-and-ventures/assets/161372702/5ccc7025-259f-4e5d-b84b-cbbb173cb83c)

**Comment by PabloDnSS** [comment]
Verdant i mean

**Comment by Faboslav** [comment]
Hello there, you will need to provide little bit more info, do you have any mod candidates for this behaviour (Or post full mod list)? Also are you using resource packs? Is it like this when disabled?

**Comment by PabloDnSS** [comment]
[11:30:19] [main/INFO]: Loading 526 mods:
	- abridged 1.1.1
	- additionalentityattributes 1.4.0.5+1.20.1
	- additionalstructures 4.2.1
	- advancementplaques 1.5.1
	- ags_day_counter 3.7
	- aiimprovements 0.5.2
	- alexscaves 1.1.4
	- alexsdelight 1.5
	- alexsmobs 1.22.8
	- all_bark_all_bite 1.20.1-1.0.2
	- amecsapi 1.5.3+mc1.20-pre1
	- amendments 1.20-1.1.10
	- ancient_manuscripts 1.1.4-1.20.1
	- apoli 1.20.1-2.9.0.6
	- apotheosis 7.3.3
	- apotheotic_additions 2.0.1
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.1
	- aquaculturedelight 1.0.0
	- aquamirae 6.API15
	- aquatictorches 1.1.1
	- archbows 1.1.9-1.20.1
	- archers_paradox 5.0.0
	- architectury 9.2.14
	- areas 5.6
	- artifacts 9.3.0
	- atlaslib 1.1.10b
	- attributefix 21.0.4
	- attributeslib 1.3.3
	- autoleveling 1.19b
	- autoreglib 1.8.2-55
	- awesomedungeonocean 3.3.0
	- badpackets 0.4.3
	- bagus_lib 1.20.1-4.4.0
	- bakery 1.1.3
	- balm 7.2.2
	- bclib 3.0.14
	- beachparty 1.1.3
	- beautify 2.0.2
	- beekeeperhut 2.0.0
	- bellsandwhistles 0.4.3-1.20.x
	- betteradvancements 0.3.2.162
	- betterarcheology 1.1.7-1.20.1
	- betterburning 9.0.2
	- bettercombat 1.8.4+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Forge-2.0.6
	- betterf3 7.0.2
	- betterfortresses 1.20-Forge-2.0.6
	- betterfpsdist 1.20.1-4.3
	- bettergolem 1.20.1-4.0.1
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betternether 9.0.10
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterthirdperson 1.9.0
	- bettertridents 8.0.1
	- bettervillage 3.1.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- bfendcities 1.0
	- biomemusic 1.20.1-2.3
	- biomesoplenty 18.0.0.592
	- blocky_siege 6.1.92
	- bno 9.1.1
	- bookshelf 20.1.9
	- born_in_chaos_v1 1.0.0
	- bountiful 6.0.3+1.20.1
	- bowinfinityfix 2.6.0
	- brewery 1.1.4
	- brutalbosses 1.20.1-6.8
	- bygonenether 1.3.2
	- caelus 3.1.0+1.20
	- calio 1.20.1-1.11.0.3
	- candlelight 1.2.8
	- cannibal 1.0.5-1.20.1
	- carryon 2.1.2.7
	- cavedust 2.0.1
	- caveore 1.20.1-3.6
	- cavernousdelight 1.1.0
	- cdl 2.2.2
	- charmofundying 6.5.0+1.20.1
	- chefsdelight 1.0.3-forge-1.20.1
	- citadel 2.5.4
	- citresewn 1.20.1-5
	- clientcrafting 1.20.1-1.8
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- cofh_core 11.0.0
	- collective 7.40
	- com_github_llamalad7_mixinextras 0.2.2
	- connectedglass 1.1.11
	- connectivity 1.20.1-5.5
	- connectorextras 1.10.0+1.20.1
	- connectorextras_architectury_bridge 1.10.0+1.20.1
	- connectorextras_continuity_compat 1.10.0+1.20.1
	- connectorextras_emi_bridge 1.10.0+1.20.1
	- connectorextras_energy_bridge 1.10.0+1.20.1
	- connectorextras_geckolib_fabric_compat 1.10.0+1.20.1
	- connectorextras_jei_bridge 1.10.0+1.20.1
	- connectorextras_kubejs_bridge 1.10.0+1.20.1
	- connectorextras_modmenu_bridge 1.10.0+1.20.1
	- connectorextras_pehkui_bridge 1.10.0+1.20.1
	- connectorextras_rei_bridge 1.10.0+1.20.1
	- connectorextras_terrablender_bridge 1.10.0+1.20.1
	- connectormod 1.0.0-beta.36+1.20.1
	- controlling 12.0.2
	- corgilib 4.0.1.1
	- corn_delight 1.0.3-1.20.1
	- coroutil 1.20.1-1.3.7
	- corpse 1.20.1-1.0.12
	- cosmeticarmorreworked 1.20.1-v1a
	- cozy_home 3.0.2
	- crabbersdelight 1.1.4
	- craftable_flint_from_gravel 1.0.0
	- craftable_orb_of_origin 1.0.0
	- craftablevillagerspawnegg 1.0.0
	- cratedelight 1.0.7-1.20.1-forge
	- create 0.5.1.f
	- create_central_kitchen 1.3.10
	- create_compressed 1.0.1
	- create_confectionery 1.1.0
	- create_crush_everything 1.0.2
	- create_dragon_lib 1.3.3
	- create_oppenheimered 1.0.2
	- create_sa 2.0.4.
	- create_structures 0.1.1
	- create_things_and_misc 1.0.0
	- createaddition 1.20.1-1.2.3
	- creativecore 2.11.25
	- creeperoverhaul 3.0.2
	- cristellib 1.1.5
	- croptopia 3.0.4
	- croptopia_delight 1.0
	- ctov 3.4.2
	- cupboard 1.20.1-2.6
	- curios 5.7.2+1.20.1
	- curioscompat 1.0.0
	- cutthrough 8.0.2
	- damageindicator 1.0.0-1.20.1
	- damagenumbers 1.1.0-forge
	- decorative_blocks 4.1.3
	- defaultresources 2.0.0
	- delightful 3.5.2
	- divine_weaponry 1.6.0
	- doapi 1.2.8
	- domesticationinnovation 1.7.1
	- dragonfight 1.20.1-4.4
	- dragonmounts 1.1.5.b3
	- dsurround 0.3.3
	- dummmmmmy 1.20-1.8.14
	- dungeons_enhanced 5.2.2
	- dynamic_asset_generator 4.2.2
	- dynamiclightsreforged 1.20.1_v1.6.0
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- eatanomelette 1.4.0
	- ecologics 2.2.0
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.9+mc1.20.1
	- enchdesc 17.0.14
	- endermanoverhaul 1.0.4
	- endersdelight 1.0.3
	- endrem 5.2.3-R-1.20.1
	- enhanced_snowman 1.1.3
	- enhancedvisuals 1.6.9
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2
	- epherolib 0.1.2
	- equipmentcompare 1.3.7
	- euphoria_patcher 0.3.0-forge
	- everycomp 1.20-2.6.37
	- excavated_variants 3.0.9
	- expandability 9.0.0
	- explorerscompass 1.20.1-1.3.3-forge
	- explorify 1.3.0-mc1.20
	- explosiveenhancement 1.2.2-1.20.x
	- extra_compat 1.4.8
	- eyesinthedarkness 1.3.10
	- fabric_api 0.92.0+1.11.3+1.20.1
	- fabric_api_base 0.4.31+ef105b4977
	- fabric_api_lookup_api_v1 1.6.36+67f9824077
	- fabric_biome_api_v1 13.0.13+dd0389a577
	- fabric_block_api_v1 1.0.11+0e6cb7f777
	- fabric_block_view_api_v2 1.0.1+0767707077
	- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
	- fabric_client_tags_api_v1 1.1.2+5d6761b877
	- fabric_command_api_v1 1.2.34+f71b366f77
	- fabric_command_api_v2 2.2.13+561530ec77
	- fabric_content_registries_v0 4.0.11+a670df1e77
	- fabric_convention_tags_v1 1.5.5+fa3d1c0177
	- fabric_data_attachment_api_v1 1.0.0+30ef839e77
	- fabric_data_generation_api_v1 12.3.4+369cb3a477
	- fabric_dimensions_v1 2.1.54+8005d10d77
	- fabric_entity_events_v1 1.6.0+6274ab9d77
	- fabric_events_interaction_v0 0.6.2+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.40+683d4da877
	- fabric_item_api_v1 2.1.28+2272fc7f77
	- fabric_item_group_api_v1 4.0.12+c9161c2d77
	- fabric_key_binding_api_v1 1.0.37+561530ec77
	- fabric_lifecycle_events_v1 2.2.22+afab492177
	- fabric_loot_api_v2 1.2.1+eb28f93e77
	- fabric_message_api_v1 5.1.9+52cc178c77
	- fabric_mining_level_api_v1 2.1.50+561530ec77
	- fabric_model_loading_api_v1 1.0.3+6274ab9d77
	- fabric_models_v0 0.4.2+7c3892a477
	- fabric_networking_api_v1 1.3.11+503a202477
	- fabric_object_builder_api_v1 11.1.3+2174fc8477
	- fabric_particles_v1 1.1.2+78e1ecb877
	- fabric_recipe_api_v1 1.0.21+514a076577
	- fabric_registry_sync_v0 2.3.3+1c0ea72177
	- fabric_renderer_api_v1 3.2.1+1d29b44577
	- fabric_renderer_indigo 1.5.1+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
	- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
	- fabric_rendering_v1 3.0.8+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
	- fabric_resource_loader_v0 0.11.10+cefbb70477
	- fabric_screen_api_v1 2.0.8+45a670a577
	- fabric_screen_handler_api_v1 1.3.30+561530ec77
	- fabric_sound_api_v1 1.0.13+4f23bd8477
	- fabric_transfer_api_v1 3.3.4+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- fallingleaves 2.1.0
	- fallingtree 4.3.4
	- farmersdelight 1.20.1-1.2.4
	- farmersutils 1.0.5-1.20.1
	- fastbench 8.0.4
	- fasterladderclimbing 0.2.10
	- fastfurnace 8.0.2
	- fastleafdecay 31
	- ferritecore 6.0.1
	- flib 0.0.11
	- flowerymooblooms 2.0.1
	- flywheel 0.6.10-7
	- footprintparticle 0.5.1-mc1.20
	- forge 47.2.20
	- forgeconfigapiport 8.0.0
	- forgeconfigscreens 8.0.2
	- formations 1.0.2
	- formationsnether 1.0.3
	- formationsoverworld 1.0.2
	- framework 0.6.27
	- friendsandfoes 2.0.10
	- fusion 1.1.1
	- geckolib 4.4.4
	- giants_overhaul 1.4.2
	- goblintraders 1.9.3
	- goldenfoods 2.2.0
	- golemsarefriends 1.20.0-1.0.1
	- gpumemleakfix 1.20.1-1.8
	- grassoverhaul 23.10.10
	- graveyard 3.1
	- guardvillagers 1.20.1-1.6.4
	- guiclock 4.4
	- handcrafted 3.0.6
	- harderspawners 46.25.1
	- healingcampfire 5.3
	- hearths 1.0.0-mc1.20u1.20.1
	- herbalbrews 1.0.5
	- highlighter 1.1.9
	- hopo 1.1.8
	- hoporp 1.3.7
	- hopour 1.1.4
	- hordes 1.4.0
	- horror_element_mod 1.5.8
	- huskspawn 3.5
	- iceberg 1.1.21
	- idas 1.9.1+1.20.1
	- illagerinvasion 8.0.4
	- immediatelyfast 1.2.10+1.20.4
	- immersive_aircraft 0.7.5+1.20.1
	- immersive_armors 1.6.1+1.20.1
	- immersive_melodies 0.1.0+1.20.1
	- immersive_weathering 1.20.1-2.0.1
	- improvedmobs 1.20.1-1.12.1
	- infernalmobs 1.20.1.2
	- integrated_api 1.4.2+1.20.1-forge
	- integrated_stronghold 1.1.1+1.20.1-forge
	- inventoryhud 3.4.18
	- irisflw 1.20.1-0.2.4
	- item_obliterator 1.7.0
	- itemborders 1.2.1
	- itemproductionlib 1.0.2a
	- jade 11.7.1
	- jadeaddons 5.2.2
	- jeed 1.20-2.1.12
	- jei 15.9999
	- jeresources 1.4.0.247
	- jrftl 1.6.0
	- kambrik 6.1.1+1.20.1
	- kelpfertilizer 3.2
	- kiwi 11.5.5
	- knavesneeds 2.0+1.20.1
	- kotlinforforge 4.10.0
	- leavesbegone 8.0.0
	- legendarytooltips 1.4.5
	- letmedespawn 1.2.0
	- libraryferret 4.0.0
	- lithostitched 1.1.5
	- looot 1.2.0.4
	- lootbeams 1.20.1
	- lootintegrations 1.20.1-3.4
	- lootr 0.7.32.79
	- lunar 0.1.10
	- majruszlibrary 7.0.5
	- majruszsaccessories 1.5.2
	- make_bubbles_pop 0.2.0-forge
	- map_atlases 1.20-6.0.3
	- masiks_puzzle_dungeon 1.2.0
	- maxhealthfix 12.0.2
	- mcpitanlib 2.2.3-1.20.1-forge
	- mcwpaintings 1.0.5
	- medievalend 1.0.0
	- memoryleakfix 1.1.5
	- merchantmarkers 1.3.3
	- mes 1.3-1.20-forge
	- milkallthemobs 3.2
	- minecraft 1.20.1
	- miners_delight 1.20.1-1.2.3
	- missingwilds 1.2.1+1.20.1
	- mixinextras 0.3.5
	- mixinsquared 0.1.1
	- mobcaptains 3.2.1
	- modelfix 1.14
	- moderately_enough_effect_desc 3.3.0
	- modernfix 5.14.0+mc1.20.1
	- modmenu 7.2.2
	- monolib 1.0.0
	- moonlight 1.20-2.11.4
	- more_underground_structures 7.1.0
	- morebows 1.0.13
	- morediscs 1.20.1-33-forge
	- moreleads 1.1.0
	- moremobgriefingoptions 2.0.4
	- moremobvariants 1.2.2
	- mr_camps_castles_carriages 2.2
	- mr_ctov_createstructures 1.0
	- mr_dungeons_andtaverns 3.0.3
	- mr_dungeons_andtavernsancientcityoverhaul 1
	- mr_dungeons_andtavernsswamphutrework 1
	- mr_edf_remastered 4.3
	- mr_just_anotherstructurepack 1.5
	- mr_lost_libraries 1.1.1
	- mr_mine_treasure 1.3.2
	- mr_rpg_origins 1.4.0
	- mr_tidal_towns 1.2
	- mr_villager_transportation 1.2
	- msmlegacy 2.0.4
	- multimine 1.20.1.3
	- mutil 6.1.1
	- mysterious_mountain_lib 1.4.4-1.20.1
	- mysticaloaktree 1.20-1.11
	- mythicmounts 20.1-7.4.2-forge
	- nameless_trinkets 1.20.1-1.7.8
	- naturallychargedcreepers 3.4
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- netherportalfix 13.0.1
	- netherportalspread 8.1
	- nethers_exoticism 1.2.7
	- nethersdelight 1.20.1-4.0
	- nethervinery 1.2.7
	- nightconfigfixes 8.0.0
	- no_hurt_cam 1.2
	- nocubescreateexp 1.0.3
	- non_wandering_trader 1.0.1
	- notenoughcrashes 4.4.7+1.20.1
	- nucleus 1.0.0
	- nutritiousmilk 3.3
	- nyctophobia 1.6
	- nyfsspiders 2.1.1
	- obscure_api 15
	- oceansdelight 1.0.2-1.20
	- oculus 1.6.15a
	- oregrowth 1.0.11
	- org_json_json 20090211
	- org_openjdk_nashorn_nashorn_core 15.4
	- origins 1.20.1-1.10.0.7
	- origins_classes 1.2.1
	- overflowingbars 8.0.0
	- overweight_farming 1.20.1-2.1.0-forge
	- passablefoliage 8.2.1
	- passiveshield 3.4
	- patched 3.2.3+1.20.1
	- patchouli 1.20.1-84-FORGE
	- permanentsponges 8.1.1
	- phantom 20.1.5
	- philipsruins 3.4
	- physicsmod 3.0.13
	- pickupnotifier 8.0.0
	- placeablesmod 1.8
	- placebo 8.6.1
	- playeranimator 1.0.2-rc1+1.20
	- playerrevive 2.0.24
	- plenty_of_golems 1.3.0
	- polymorph 0.49.2+1.20.1
	- portablehole 8.0.0
	- pots_and_mimics 1.0.2
	- prism 1.0.5
	- projectvibrantjourneys 1.20.1-6.0.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.17
	- qualitysounds 1.5.0
	- quark 4.0-438
	- quarkdelight 1.0.0
	- radiantgear 2.1.4+1.20.1
	- radium 0.12.2+git.5f80f74
	- raided 0.1.4
	- railways 1.5.3+forge-mc1.20.1
	- randomvillagenames 3.5
	- rare_ice 0.0NONE
	- ravageandcabbage 1.2.3
	- reach_entity_attributes 2.4.0
	- realmrpg_creep 1.0.2
	- realmrpg_skeletons 1.0.3
	- realmrpg_wyrms 1.0.1
	- recruits 1.10.15
	- reeses_sodium_options 1.0.4
	- regions_unexplored 0.5.5
	- rei_plugin_compatibilities 12.0.93
	- repurposed_structures 7.1.13+1.20.1-forge
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	- respawningstructures 1.20.1-2.5
	- respawnobelisks 2.4-d
	- revampedwolf 1.20.1-5.0.0
	- rightclickharvest 3.2.3+1.20.1-forge
	- ringsofascension 2.0.0
	- roughlyenoughitems 12.0.684
	- roughlyenoughprofessions 2.0.2
	- roughlyenoughresources 2.9.0
	- rrls 3.2.0-1.20.1-forge
	- rubidium 0.7.1
	- scalinghealth 0.0NONE
	- sculkhorde 1.20.1-0.9.0-Beta5
	- seadwellers 2.9.9
	- searchables 1.0.2
	- seedbags 1.0.0
	- shield_overhaul 1.0.3
	- shouldersurfing 1.20.1-2.9.6
	- silentlib 8.0.0
	- simplyswords 1.54.0-1.20.1
	- skeletonhorsespawn 3.8
	- skilltree 0.6.11
	- sleep_tight 1.20-1.1.19
	- sliceanddice 3.2.0
	- smallships 2.0.0-b1.1
	- smartbrainlib 1.13
	- smarterfarmers 1.20-1.8.3
	- solcarrot 1.15.1
	- sophisticatedbackpacks 3.20.3.1034
	- sophisticatedcore 0.6.11.578
	- sound_physics_remastered 1.20.1-1.3.1
	- sparsestructuresreforged 1.20.1-0.0.1
	- spawnanimations 1.9.4+mod
	- spectrelib 0.13.14+1.20.1
	- spellbound_weapons_mr 4.0.5l
	- spelunkers_charm 3.5.8
	- spidersproducewebs 3.3
	- spyglass_improvements 1.5+mc1.20+forge
	- starterkit 6.5
	- storagedrawers 12.0.3
	- string_from_wool 1.0.0
	- structory 1.3.4
	- structorytowers 1.0.6
	- structure_gel 2.16.1
	- structureessentials 1.20.1-3.3
	- stylisheffects 8.0.2
	- subterrestrial 2.2.0
	- sunflowerdelight 1.0.1
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.6
	- suppsquared 1.20-1.1.14
	- t_and_t 0.0NONE
	- tact 1.1.1
	- takesapillage 1.0.3
	- temporalapi 1.5.0
	- tenshilib 1.20.1-1.7.4
	- terrablender 3.0.1.4
	- terraform 7.0.1
	- terralith 2.4.11
	- textrues_embeddium_options 0.1.5+mc1.20.1
	- theorcs 1.0-FORGE-1.20.x
	- thirst 1.3.5
	- toofast 0.4.3.5
	- toolbelt 1.20.0
	- toolleveling 1.20.1-2.0.0
	- torchflower_relit 1.0.0
	- travelerstitles 1.20-Forge-4.0.2
	- treasuredistance 1.20-1.2
	- trolldom 2.0.1
	- tumbleweed 0.5.5
	- universalbonemeal 8.0.1
	- universalenchants 8.0.0
	- useless_sword 1.4.1
	- v_slab_compat 1.20-2.3
	- valhelsia_core 1.1.1
	- valhelsia_furniture 1.1.2
	- valhelsia_structures 1.20.1-1.1.1
	- variantsandventures 1.0.1
	- villagernames 7.3
	- villagersplus 3.1
	- villagesandpillages 1.0.0
	- vinery 1.4.11
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- wabi_sabi_structures 2.0.0-1.20
	- wandering_bags 2.0.7
	- wardrobe 1.0.3
	- waterdripsound 0.3.2
	- watut 1.20.1-1.1.0
	- waystones 14.1.3
	- weaponleveling 1.20.1-2.1.1
	- workers 1.7.7
	- wunderlib 1.1.5
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- yet_another_config_lib_v3 3.2.2+1.20
	- yungsapi 1.20-Forge-4.0.4
	- yungsextras 1.20-Forge-4.0.3
	- zeta 1.0-14
	- zombieawareness 1.20.1-1.13.1
	- zombiehorsespawn 4.8

**Comment by PabloDnSS** [comment]
this is the only entity with this issue

**Comment by Faboslav** [comment]
This is just too long mod list for me to try disabling one mod by one mod, i am not sure what to do here, what about the resource packs?

**Comment by PabloDnSS** [comment]
Okay my bad i should have seen this mistake myself whitout bothering you it is better skeleton resource pack incompatibility

**Comment by Faboslav** [comment]
Dont worry about it, i am glad that its working now :).
