### ISSUE TITLE
Direwolf20 1.21 V1.3.0 Crashing

### ISSUE THREAD

**Issue by xAphex** [Faboslav/variants-and-ventures#30]
### Minecraft version information

1.21.1

### Mod loader information

NeoForge

### Mod loader version information

21.1.69

### Mod version information

1.0.6

### Reproduction Steps

1. Launch direwolf20 1.21.1 V1.3.0.
2. Game crashes.

### Crash Report and latest.log

- Crash Report: https://mclo.gs/XtDnpPS
- latest.log: https://mclo.gs/dlMrqgB
- Prism Log: https://mclo.gs/LFXa7JM

**Comment by Faboslav** [comment]
Hello, i looked into this, but i have zero idea what is wrong based on the logs, seems like something related to combination of `iris` and `MixinHumanoidArmorLayer` whatever that is

**Comment by xAphex** [comment]
> Hello, i looked into this, but i have zero idea what is wrong based on the logs, seems like something related to combination of `iris` and `MixinHumanoidArmorLayer` whatever that is

after updating `iris` to latest version which includes fixed for `NeoForge 21.1.62` the game launches now.
