### ISSUE TITLE
Variants and Ventures fails to load

### ISSUE THREAD

**Issue by Sunconure11** [Faboslav/variants-and-ventures#4]
### Minecraft version information

1.19.2

### Mod loader information

Quilt

### Mod loader version information

Quilt 0.24.0

### Mod version information

variantsandventures-mc1.19.2-1.0.1

### Reproduction Steps

1. Attempt start up
2. ???
3. This

### Crash Report and latest.log

https://gist.github.com/Sunconure11/fa5a0ab020ef3a59d570c77b9139c09b

### Additional information

Heavily modded pack

**Comment by Faboslav** [comment]
You need to download and use the `Quilted Fabric API` mod https://www.curseforge.com/minecraft/mc-mods/qsl.

**Comment by Sunconure11** [comment]
I am using it, but I had to downgrade to a slightly older version while I wait on some mods to update to the newer version.

**Comment by Faboslav** [comment]
So is it working when downgraded?

**Comment by Sunconure11** [comment]
No.

**Comment by Faboslav** [comment]
Okay and when non downgraded does it work, because this report is not a crash nor error, that is just bad version of your dependency

**Comment by Faboslav** [comment]
Let me know if there is anything new or more context, i cant do anything based on current info, i am sorry :).
