### ISSUE TITLE
Mob sounds are a little louder

### ISSUE THREAD

**Issue by Mechalopa** [Faboslav/variants-and-ventures#5]
### Minecraft version information

1.20.4

### Mod loader information

NeoForge

### Mod loader version information

20.4.210

### Mod version information

1.0.1

### Expected Behavior

All of mobs sound louder than the vanilla mobs.

### Actual Behavior

Turns down the sound of mobs.

### Reproduction Steps

Summon or punch mobs

**Comment by Faboslav** [comment]
Are you sure it's all the sounds? For example for Verdant, ambient sound is louder for sure, but hurting the mob is the same by my tests.

**Comment by Mechalopa** [comment]
Yes, only personally I think so...

**Comment by Faboslav** [comment]
Should be resolved(maybe least partially) with 1.0.2 version.
