### ISSUE TITLE
Tags needed

### ISSUE THREAD

**Issue by Mechalopa** [Faboslav/variants-and-ventures#6]
### Minecraft version information

1.20.4

### Mod loader information

NeoForge

### Mod loader version information

20.4.210

### Mod version information

1.0.1

### Expected Behavior

Verdant is not registered in `minecraft:skeletons` tag, and gelid and thicket are not registered in `minecraft:zombies` tag.

### Actual Behavior

Add verdant to `minecraft:skeletons` entity type tag.
If mc1.20.3 or later, add gelid and thicket to `minecraft:zombies` entity type tag.

### Reproduction Steps

Check the mob's tag on the debug screen.

**Comment by Faboslav** [comment]
Hello there, i will add both of these, thanks for pointing out!

**Comment by Faboslav** [comment]
Will be added with https://github.com/Faboslav/variants-and-ventures/pull/7.

**Comment by Faboslav** [comment]
Should be resolved with 1.0.2 version.
