### ISSUE TITLE
Unnecessary creative tab

### ISSUE THREAD

**Issue by thwonn** [Faboslav/variants-and-ventures#8]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.15.7

### Mod version information

1.0.1

### Expected Behavior

Items should be placed in relevant existing creative tabs.

### Actual Behavior

There is a separate tab for this mod's items.

### Reproduction Steps

1. Open Creative inventory 2. Flip pages until you find "Variants & Ventures" tab

**Comment by Faboslav** [comment]
This is by choice, not a bug, also all items are already available in their relevant tabs.

**Comment by thwonn** [comment]
Could there be a configuration option to remove the creative tab? Itʼs causing problems in a modpack Iʼm making.

**Comment by Faboslav** [comment]
How is that causing a problem? I would like to have more info/context

**Comment by thwonn** [comment]
Itʼs just a small problem
It makes fabric display the second page thing thatʼs not compatible with a resource pack Iʼm using.
Could also be fixed by adding a few textures to the resource pack

**Comment by Faboslav** [comment]
Hmm, as I dont want to do these kind of customizations, so if this is solvable by resource pack or data pack or some third party mod, go for that, hopefully you will be able to get your desired output :).

**Comment by thwonn** [comment]
I can probably just use [MoreCreativeTabs](https://modrinth.com/mod/morecreativetabs) or something like that

**Comment by KreloX** [comment]
a separate tab for 4 items 💀
